### PR TITLE
Updates on USE_OTHER_TIME_FUNCTION

### PR DESCRIPTION
**Pull request by homnath**

### CODE REVIEW

**Comment by homnath** [comment]
Interestingly, "Test_run_example 4 - small adjoint" runs fine on my side!

**Comment by casarotti** [comment]
Is there any update on this topic? I was considering include the Yoffe STF in the loop

**Comment by danielpeter** [comment]
the patch above didn't make it into the devel version yet.

for force point sources (`FORCESOLUTION`), the Brune & smoothed Brune functions are implemented by using the setting `source time function: 5` (or `6`) in the `FORCESOLUTION` file. the above PR would have added a `Par_file` flag to achieve the same for `CMTSOLUTION` sources. a new pull request would need to be submitted for that.

**Comment by homnath** [comment]
Let me take another look at this 🙂

Best,
Hom Nath



---------------------------------------
Hom Nath Gharti, PhD
Assistant Professor | Digital Earth Scientist
https://www.digitalearthscience.com/
Department of Geological Sciences and Geological Engineering
Miller Hall 314, 36 Union St
Queen’s University
Kingston, ON K7L 3N6, Canada


Queen’s University is situated on traditional
Anishinaabe and Haudenosaunee Territory.<https://www.queensu.ca/encyclopedia/t/traditional-territories>
________________________________

**Comment by adunham1** [comment]
@homnath Just wanted to chime in here, we worked together on this implementation about a year ago and I am currently using a working version for the smooth brune STF with a CMTSOLUTION for my simulations, I believe from your specfem3d fork. It would be great to see this new parameter in the devel version, I'm happy to help/run tests, just let me know!

**Comment by homnath** [comment]
Thanks, Audrey! Stay tuned.

Best,
Hom Nath


---------------------------------------
Hom Nath Gharti, PhD
Assistant Professor | Digital Earth Scientist
https://www.digitalearthscience.com/
Department of Geological Sciences and Geological Engineering
Miller Hall 314, 36 Union St
Queen’s University
Kingston, ON K7L 3N6, Canada


Queen’s University is situated on traditional
Anishinaabe and Haudenosaunee Territory.<https://www.queensu.ca/encyclopedia/t/traditional-territories>
________________________________

**Pull request closed without merging**
