### PR TITLE
Fix HIP_PLATFORM macros

### PR DESCRIPTION
**Pull request by gargrahul**
Replace __HIP_PLATFORM_HCC__ to __HIP_PLATFORM_AMD__ and __HIP_PLATFORM_NVCC__ to __HIP_PLATFORM_NVIDIA__

### CODE REVIEW

**Comment by danielpeter** [comment]
update for latest ROCm platform 5.7.1 version:
https://rocm.docs.amd.com/projects/HIP/en/latest/user_guide/hip_porting_guide.html#identifying-hip-target-platform

**Comment by pramenku** [comment]
Hi @danielpeter When this PR can be merged to master branch?

**Comment by danielpeter** [comment]
there is no scheduled release yet (the master branch is the "official" release). however, I thought to update the master soon - somewhen in november. do you have any preference/dependence on this master release?

**Comment by pramenku** [comment]
@danielpeter yes, We use master branch to test internally.
So before next rocm gets released, we want to make sure, it has been properly tested.
If you can merge by this week or early next week, will.be great help.

**Pull request merged**
