### PR TITLE
updates tomography file reading, FK coupling and parallel decomposer

### PR DESCRIPTION
**Pull request by danielpeter**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by danielpeter** [comment]
accept

On 13 Apr 2023, at 16:51, buildbot-princeton ***@***.******@***.***>> wrote:



The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by danielpeter** [comment]
new buildbot feature? let's try again manually...

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Pull request closed without merging**
