### PR TITLE
Diffusion-PDE-based smoothing

### PR DESCRIPTION
**Pull request by tianshi-liu**
An fast implementation of smoothing based on diffusion PDE, similar to laplacian_smoothing_sem in SPECFEM3D_Globe, but with a different implementation. It performs smoothing by solving diffusion PDE with explicit time stepping, without the need to solve linear system. It has identical command-line argument with smooth_sem, and is aimed to exactly replicate the result of smooth_sem.

### CODE REVIEW

**Comment by tianshi-liu** [comment]
As a small test, I use the original xsmooth_sem and the new version xsmooth_sem_pde to smooth a Gauss function shown in the following figure:
gauss_field
Smoothing result from xsmooth_sem (running time = 255s):
gauss_field_conv
Smoothing result from xsmooth_sem_pde (running time = 1.8s):
gauss_field_pde

**Comment by tianshi-liu** [comment]
I keep getting errored Travis CI tests. Looks like all tests on ppc64le time out without receiving any output, not sure why ...

**Comment by danielpeter** [comment]
there might be some issues on travis server side... will merge and see with future PRs if this will be fixed.

**Comment by meiqgg** [comment]
Hello, @tianshi-liu xsmooth_sem_pde performs well in elastic media, but does it not support acoustic media?

**Comment by tianshi-liu** [comment]
> Hello, @tianshi-liu xsmooth_sem_pde performs well in elastic media, but does it not support acoustic media?

It should support acoustic media, but I haven't tested the acoustic case. Did you try it? If you encountered any problem, please let me know!

**Comment by meiqgg** [comment]
> > Hello, @tianshi-liu xsmooth_sem_pde performs well in elastic media, but does it not support acoustic media?您好，xsmooth_sem_pde 在弹性媒体中表现良好，但它不支持声学媒体吗？
> 
> It should support acoustic media, but I haven't tested the acoustic case. Did you try it? If you encountered any problem, please let me know!它应该支持 acoustic media，但我还没有测试过 acoustic case。您试过吗？如果您遇到任何问题，请告诉我！

Yes, I tried modifying the two places in smooth_sem_pde.F90 to use acoustic media instead of elastic. But I got errors during runtime, as shown in the third image:
Fatal error in internal_Isend: Invalid argument and Null pointer in parameter request.

This issue is quite strange, and I’m not sure where to change. If you’re willing to take a look and offer any help, I’d really appreciate it.

0da0e480-0255-46d5-a4ea-bc49e2546c1d
ff85f4b7-2e87-4e94-95c1-0d5544f49085
error
[smooth_vp.log](https://github.com/user-attachments/files/20735293/smooth_vp.log)

I’ve attached the log. If it’s convenient for you, please have a look.

**Comment by tianshi-liu** [comment]
@meiqgg I just checked my code, and unfortunately you were right. I'll fix this hopefully in one week or two and let you know. I'll also add a GPU support for PDE-based smoothing. Stay tuned!

**Comment by meiqgg** [comment]
> @meiqgg I just checked my code, and unfortunately you were right. I'll fix this hopefully in one week or two and let you know. I'll also add a GPU support for PDE-based smoothing. Stay tuned!

@tianshi-liu  Thank you very much for the confirmation and the upcoming improvements! I really appreciate your work and look forward to the fix and the GPU support.

**Comment by meiqgg** [comment]
> @meiqgg I just checked my code, and unfortunately you were right. I'll fix this hopefully in one week or two and let you know. I'll also add a GPU support for PDE-based smoothing. Stay tuned!我刚刚检查了我的代码，不幸的是你是对的。我希望在一两周内解决这个问题，然后让你知道。我还将添加对基于 PDE 的平滑的 GPU 支持。敬请期待！

@tianshi-liu  Hi, sorry to bother you. I've just seen the GPU version—great work! Just wondering—does the current GPU version (or any previous one) support acoustic media? Many thanks!

**Pull request merged**
