### PR TITLE
Phdf5 ioserver merge to upstream

### PR DESCRIPTION
**Pull request by mnagaso**
Hello @danielpeter !

I finally cought up the current devel branch of upstream. So I want to merge my development for:

- parallel HDF5 support for decompose/meshfem/generate_database/specfem3d
- asynchronous IO 

A technical and brief report on the modifications are:
https://docs.google.com/document/d/1Wtoh_GCrpm6OuVOqIr1CASRXeGysxup-hxbjx3IVqYU/edit?usp=sharing

The hdf5+asyncronous IO will be only available when the code is configured with e.g.:  
`./configure FC=h5pfc MPIFC=h5pfc --with-mpi --with-hdf5`  

There are two additional parameters in Par_file below:
```
# HDF5 Database I/O flag which is useful for a massively parallelized calculation.
HDF5_ENABLED                    = .true.

# number of IO dedicated procs, available only with HDF5 output option
NIONOD                          = 0
```

Please feel free to ask me further explanation on the implementation.
I can also provide some performance test result (please send a message to my gmail if necessary).

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by buildbot-princeton** [comment]
The files changed do not require a buildbot test. The maintainers can commit these changes.

**Comment by mnagaso** [comment]
As this change is very big, maybe keeping this version as a different branch would be an option🤔

**Comment by buildbot-princeton** [comment]
You pushed to your local branch while your previous changes are waiting to be committed. We assume that you did not intend for these changes to be part of the currently opened pull-request and ignore those changes. If you want these changes to be committed, please open a new pull-request.

**Note to maintainers:** when you accept the original pull-request, the message from buildbot will say that it **closed** the pull-request, as opposed to the usual message that it **merged** the pull-request. In spite of this, the initial pull-request will be merged after you accept it.

**Comment by danielpeter** [comment]
hi Masaru-san, great work! 

there are a bunch of test problems with the current PR, so let me close this one for now. I'll put some comments in the code section just as info where I think we might change things a bit.

I would suggest that I'll take your fork version and include your modifications one by one. as far as I see, there are two main additions:
* HDF5 file format for database files
* I/O server with splitting MPI processes into compute and io tasks

let me start by including the first point, making sure that I don't break the examples and tests. then, I'll add the IO server modification in some follow-up PRs.

many thanks :)

**Comment by mnagaso** [comment]
Hi Daniel,

Thank you very much for checking my pull request !

Yes it seems that a auto-compilation test was not ok. I might write the rules.mk wrongly.

Also, I am sorry for putting two features in one PR, which I should have divided by myself.
But even only taking HDF5 I/O (the first point) into the code would be much simplify the file handling and post-processings.
(If possible, I would like to add this to SPECFEM2D as well🤔)

Please ask me anything and anytime about the parts which I wrote if you will have any questions🙇
I am very happy to be able to contribute on SPECFEM.

**Pull request closed without merging**
